### ISSUE TITLE
Tag and publish a new release?

### ISSUE THREAD

**Issue by kennethormandy** [ekalinin/typogr.js#34]
Hey, would you mind tagging a new release and pushing it to npm? Thanks!

**Comment by ekalinin** [comment]
Sure, going to do it today.
Sorry for delay.

**Comment by ekalinin** [comment]
Done:
  * https://github.com/ekalinin/typogr.js/releases/tag/0.6.6

**Comment by kennethormandy** [comment]
Wow, that was quick, thank you!

**Comment by ekalinin** [comment]
You're welcome!
