### ISSUE TITLE
handle rocknroll correctly

### ISSUE THREAD

**Issue by mheiber** [ekalinin/typogr.js#39]
Should be rock &#39;n&#39; roll instead of rock &lsquo;n&rsquo; roll. (see Markdown source for what I mean by this)

That is, the 'n' should have two apostrophes instead of an opening and single quote and closing smart quote

**Comment by mheiber** [comment]
Happy to PR for this

**Comment by ekalinin** [comment]
Hey @mheiber 

Thanks for report. 
Sure, PRs are very welcome :)
