### ISSUE TITLE
Bump version in package.json

### ISSUE THREAD

**Issue by mheiber** [ekalinin/typogr.js#41]
Can you bump the version in the package.json so we can use the latest code?

I'm hoping to use this change: https://github.com/ekalinin/typogr.js/commit/3785b50d9a9388505ce55c021ff61466f19bbd21

**Comment by ekalinin** [comment]
Done:
  * https://github.com/ekalinin/typogr.js/releases/tag/0.6.7

**Comment by mheiber** [comment]
Thanks!
